### ISSUE TITLE
Merging your own pull request...

### ISSUE THREAD

**Issue by veredrec** [FACN3/mashrou-leila#39]
Do I need to say more?... :disappointed:

**Comment by Amirk390** [comment]
I think it was because we worked on the same computer so 1 person done the pull request and the other reviewed it and merged it from the came computer :sweat_smile:

**Comment by hoslack** [comment]
Some time we worked on the same computer. So after the  first person made a PR the other merged it. We shall be more careful next time. Thank you.

**Comment by veredrec** [comment]
When you work as a pair, the other pair should merge your request :smile: 
When you work by yourself, which happens sometimes, someone else should go over your code and merge it. 
Let me know if something is not clear and I would love to explain :wink:
